.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/about.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/about.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBabout\fP"
.br
.RI "Module to print version, licence, preambles\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBabout::printlicpreamble\fP"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(string) \fBabout::version\fP"
.br
.ti -1c
.RI "type(string) \fBabout::author\fP"
.br
.ti -1c
.RI "type(string) \fBabout::date\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
