.TH "about" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
about \- Module to print version, licence, preambles\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBprintlicpreamble\fP"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(string) \fBversion\fP"
.br
.ti -1c
.RI "type(string) \fBauthor\fP"
.br
.ti -1c
.RI "type(string) \fBdate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module to print version, licence, preambles\&. 


.PP
\fBAuthor:\fP
.RS 4
Ricardo Birjukovs Canelas 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public about::printlicpreamble ()"

.PP
Birjukovs Canelas - MARETEC Public licence and preamble printer routine\&. 
.SH "Variable Documentation"
.PP 
.SS "type(string) about::author\fC [private]\fP"

.SS "type(string) about::date\fC [private]\fP"

.SS "type(string) about::version\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
