.TH "commom_modules" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commom_modules \- Module to hold all of the commonly used base modules\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Module to hold all of the commonly used base modules\&. 


.PP
\fBAuthor:\fP
.RS 4
Ricardo Birjukovs Canelas 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
