.TH "geometry::box" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry::box \- Type - point class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeometry::shape\fP\&.
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(vector) \fBsize\fP"
.br
.RI "Box size\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - point class\&. 
.SH "Member Data Documentation"
.PP 
.SS "type(vector) geometry::box::size\fC [private]\fP"

.PP
Box size\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
