.TH "geometry::line" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry::line \- Type - line class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeometry::shape\fP\&.
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(vector) \fBlast\fP"
.br
.RI "Coordinates of the end point\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - line class\&. 
.SH "Member Data Documentation"
.PP 
.SS "type(vector) geometry::line::last\fC [private]\fP"

.PP
Coordinates of the end point\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
