.TH "geometry::point" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry::point \- Type - point class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeometry::shape\fP\&.
.SH "Detailed Description"
.PP 
Type - point class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
