.TH "initialize" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
initialize \- Module with the simulation initialization related definitions and methods\&. Has one public access routine that is incharge of building the simulation space from input files\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBlinkpropertysources\fP (linksNode)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinit_properties\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBread_xml_geometry\fP (source, source_detail, geometry)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinit_sources\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinit_simdefs\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinit_caseconstants\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinit_parameters\fP (execution_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBinitmohidlagrangian\fP (xmlfilename)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SH "Detailed Description"
.PP 
Module with the simulation initialization related definitions and methods\&. Has one public access routine that is incharge of building the simulation space from input files\&. 


.PP
\fBAuthor:\fP
.RS 4
Ricardo Birjukovs Canelas 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine initialize::init_caseconstants (type(node), intent(in), pointer case_node)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private case constant parser routine\&. Builds the simulation parametric space from the input xml case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine initialize::init_parameters (type(node), intent(in), pointer execution_node)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private parameter parser routine\&. Builds the simulation parametric space from the input xml case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine initialize::init_properties (type(node), intent(in), pointer case_node)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private property xml parser routine\&. Reads the properties tab from the xml file and links these to the corresponding source 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine initialize::init_simdefs (type(node), intent(in), pointer case_node)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private simulation definitions parser routine\&. Builds the simulation geometric space from the input xml case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine initialize::init_sources (type(node), intent(in), pointer case_node)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private source definitions parser routine\&. Builds the tracer sources from the input xml case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine, public initialize::initmohidlagrangian (type(string), intent(in) xmlfilename)"

.PP
Birjukovs Canelas - MARETEC Public xml parser routine\&. Builds the simulation space from the input xml case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxmlfilename\fP 
.br
\fIxmlfilename\fP \&.xml file name 
.RE
.PP

.SS "subroutine initialize::linkpropertysources (type(node), intent(in), pointer linksNode)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private property xml parser routine\&. Reads the properties tab from the xml file and links these to the corresponding source 
.PP
\fBParameters:\fP
.RS 4
\fIparsedxml\fP 
.RE
.PP

.SS "subroutine initialize::read_xml_geometry (type(node), intent(in), pointer source, type(node), intent(in), pointer source_detail, class(\fBshape\fP), intent(inout) geometry)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private geometry xml parser routine\&. Reads a geometry from the xml depending on the geometry type of the node 
.PP
\fBParameters:\fP
.RS 4
\fIsource,geometry\fP 
.br
\fIsource\fP Working xml node
.br
\fIsource_detail\fP Working xml node details
.br
\fIgeometry\fP Geometrical object to fill 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
