.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/initialize.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/initialize.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBinitialize\fP"
.br
.RI "Module with the simulation initialization related definitions and methods\&. Has one public access routine that is incharge of building the simulation space from input files\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBinitialize::linkpropertysources\fP (linksNode)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::init_properties\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::read_xml_geometry\fP (source, source_detail, geometry)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::init_sources\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::init_simdefs\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::init_caseconstants\fP (case_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBinitialize::init_parameters\fP (execution_node)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBinitialize::initmohidlagrangian\fP (xmlfilename)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
