.TH "simulation_memory::memory_t" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulation_memory::memory_t
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBinitialize\fP"
.br
.ti -1c
.RI "procedure \fBaddsource\fP"
.br
.ti -1c
.RI "procedure \fBaddtracer\fP"
.br
.ti -1c
.RI "procedure \fBadddef\fP"
.br
.ti -1c
.RI "procedure \fBgetotal\fP"
.br
.ti -1c
.RI "procedure \fBprintout\fP => \fBprintmemory\fP"
.br
.ti -1c
.RI "procedure \fBdetailedprintout\fP => \fBprintmemorydetailed\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer \fBsize_of_sources\fP"
.br
.RI "Size of the sources in memory (bytes) "
.ti -1c
.RI "integer \fBsize_of_tracers\fP"
.br
.RI "Size of the tracers in memory (bytes) "
.ti -1c
.RI "integer \fBsize_of_defs\fP"
.br
.RI "Size of the parameters and definitions in memory (bytes) "
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure simulation_memory::memory_t::adddef ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::addsource ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::addtracer ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::detailedprintout ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::getotal ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::initialize ()\fC [private]\fP"

.SS "procedure simulation_memory::memory_t::printout ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "integer simulation_memory::memory_t::size_of_defs\fC [private]\fP"

.PP
Size of the parameters and definitions in memory (bytes) 
.SS "integer simulation_memory::memory_t::size_of_sources\fC [private]\fP"

.PP
Size of the sources in memory (bytes) 
.SS "integer simulation_memory::memory_t::size_of_tracers\fC [private]\fP"

.PP
Size of the tracers in memory (bytes) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
