.TH "simulation_globals" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulation_globals \- Module to hold the simulation global parameter classes and their methods\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBconstants_t\fP"
.br
.RI "Case Constants class\&. "
.ti -1c
.RI "type \fBfilenames_t\fP"
.br
.RI "File names class\&. "
.ti -1c
.RI "type \fBparameters_t\fP"
.br
.ti -1c
.RI "type \fBsimdefs_t\fP"
.br
.RI "Simulation definitions class\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsetparameter\fP (self, parmkey, parmvalue)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBcheck\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBprintsimparameters\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBgetintegratorname\fP (name, code)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsetgravity\fP (self, grav)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsetrho\fP (self, read_rho)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsetdp\fP (self, read_dp)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsetdt\fP (self, read_dt)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsetboundingbox\fP (self, point_, coords)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBprintsimdefs\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(prec_time), public \fBsimtime\fP"
.br
.ti -1c
.RI "type(\fBparameters_t\fP), public \fBparameters\fP"
.br
.ti -1c
.RI "type(\fBsimdefs_t\fP), public \fBsimdefs\fP"
.br
.ti -1c
.RI "type(\fBconstants_t\fP), public \fBconstants\fP"
.br
.ti -1c
.RI "type(\fBfilenames_t\fP), public \fBfilenames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Module to hold the simulation global parameter classes and their methods\&. 


.PP
\fBAuthor:\fP
.RS 4
Ricardo Birjukovs Canelas 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine simulation_globals::check (class(\fBparameters_t\fP), intent(inout) self)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private parameter checking method\&. Checks if mandatory parameters were set 
.SS "subroutine simulation_globals::getintegratorname (type(string), intent(inout) name, integer, intent(in) code)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC private routine to get integrator scheme name 
.SS "subroutine simulation_globals::printsimdefs (class(\fBsimdefs_t\fP), intent(in) self)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Public simulation definitions printing routine\&. 
.SS "subroutine simulation_globals::printsimparameters (class(\fBparameters_t\fP), intent(inout) self)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private parameter printing method\&. 
.SS "subroutine simulation_globals::setboundingbox (class(\fBsimdefs_t\fP), intent(inout) self, type(string), intent(in) point_, type(vector) coords)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private bounding box setting routine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpoint_,coords\fP 
.RE
.PP

.SS "subroutine simulation_globals::setdp (class(\fBsimdefs_t\fP), intent(inout) self, type(string), intent(in) read_dp)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private dp setting routine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIread_dp\fP 
.RE
.PP

.SS "subroutine simulation_globals::setdt (class(\fBsimdefs_t\fP), intent(inout) self, type(string), intent(in) read_dt)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private dt setting routine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIread_dt\fP 
.RE
.PP

.SS "subroutine simulation_globals::setgravity (class(\fBconstants_t\fP), intent(inout) self, type(vector) grav)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Public Gravity setting routine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgrav\fP 
.RE
.PP

.SS "subroutine simulation_globals::setparameter (class(\fBparameters_t\fP), intent(inout) self, type(string), intent(in) parmkey, type(string), intent(in) parmvalue)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Private parameter setting method\&. Builds the simulation parametric space from the input case file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparmkey,parmvalue\fP 
.RE
.PP

.SS "subroutine simulation_globals::setrho (class(\fBconstants_t\fP), intent(inout) self, type(string), intent(in) read_rho)\fC [private]\fP"

.PP
Birjukovs Canelas - MARETEC Provate Rho_Ref setting routine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIread_rho\fP 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "type(\fBconstants_t\fP), public simulation_globals::constants"

.SS "type(\fBfilenames_t\fP), public simulation_globals::filenames"

.SS "type(\fBparameters_t\fP), public simulation_globals::parameters"

.SS "type(\fBsimdefs_t\fP), public simulation_globals::simdefs"

.SS "real(prec_time), public simulation_globals::simtime"

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
