.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_xmlparser.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_xmlparser.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsimulation_xmlparser\fP"
.br
.RI "Module with the simulation xml parsing related definitions and routines\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsimulation_xmlparser::readxmlatt\fP (xmlnode, tag, att_name, att_value, mandatory)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBsimulation_xmlparser::readxmlvector\fP (xmlnode, tag, vec, mandatory)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBsimulation_xmlparser::gotochildnode\fP (currentNode, targetNode, targetNodeName, mandatory)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
