.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_logger.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_logger.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsimulation_logger\fP"
.br
.RI "Module to hold all the simulation logger related definitions and methods\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsimulation_logger::gettimestamp\fP (timestamp)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBsimulation_logger::tolog\fP (tologstr, timeoption)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBsimulation_logger::initmohidlagrangianlog\fP (outpath)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBsimulation_logger::log_unit\fP = \-1"
.br
.RI "'Number' of log file "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
