.TH "simulation_globals::parameters_t" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulation_globals::parameters_t
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBsetparameter\fP"
.br
.ti -1c
.RI "procedure \fBcheck\fP"
.br
.ti -1c
.RI "procedure \fBprintout\fP => \fBprintsimparameters\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer \fBintegrator\fP = 1"
.br
.RI "Integration Algorithm 1:Verlet, 2:Symplectic, 3:RK4 (default=1) "
.ti -1c
.RI "real(prec) \fBcfl\fP = 0\&.5"
.br
.RI "Courant Friedrichs Lewy condition number\&. "
.ti -1c
.RI "real(prec) \fBwarmuptime\fP = 0\&.0"
.br
.RI "Time to freeze the tracers at simulation start (warmup) (s) (default=0\&.0) "
.ti -1c
.RI "real(prec) \fBtimemax\fP = MV"
.br
.RI "Simulation duration (s) "
.ti -1c
.RI "real(prec) \fBtimeout\fP = MV"
.br
.RI "Time out data (1/Hz) "
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure simulation_globals::parameters_t::check ()\fC [private]\fP"

.SS "procedure simulation_globals::parameters_t::printout ()\fC [private]\fP"

.SS "procedure simulation_globals::parameters_t::setparameter ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "real(prec) simulation_globals::parameters_t::cfl = 0\&.5\fC [private]\fP"

.PP
Courant Friedrichs Lewy condition number\&. 
.SS "integer simulation_globals::parameters_t::integrator = 1\fC [private]\fP"

.PP
Integration Algorithm 1:Verlet, 2:Symplectic, 3:RK4 (default=1) 
.SS "real(prec) simulation_globals::parameters_t::timemax = MV\fC [private]\fP"

.PP
Simulation duration (s) 
.SS "real(prec) simulation_globals::parameters_t::timeout = MV\fC [private]\fP"

.PP
Time out data (1/Hz) 
.SS "real(prec) simulation_globals::parameters_t::warmuptime = 0\&.0\fC [private]\fP"

.PP
Time to freeze the tracers at simulation start (warmup) (s) (default=0\&.0) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
