.TH "simulation_globals::filenames_t" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulation_globals::filenames_t \- File names class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(string) \fBmainxmlfilename\fP"
.br
.RI "Input \&.xml file name\&. "
.ti -1c
.RI "type(string) \fBpropsxmlfilename\fP"
.br
.RI "Properties \&.xml file name\&. "
.in -1c
.SH "Detailed Description"
.PP 
File names class\&. 
.SH "Member Data Documentation"
.PP 
.SS "type(string) simulation_globals::filenames_t::mainxmlfilename\fC [private]\fP"

.PP
Input \&.xml file name\&. 
.SS "type(string) simulation_globals::filenames_t::propsxmlfilename\fC [private]\fP"

.PP
Properties \&.xml file name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
