.TH "simulation_globals::constants_t" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simulation_globals::constants_t \- Case Constants class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBsetgravity\fP"
.br
.ti -1c
.RI "procedure \fBsetrho\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(vector) \fBgravity\fP"
.br
.RI "Gravitational acceleration vector (default=(0 0 -9\&.81)) (m s-2) "
.ti -1c
.RI "real(prec) \fBrho_ref\fP = 1000\&.0"
.br
.RI "Reference density of the medium (default=1000\&.0) (kg m-3) "
.in -1c
.SH "Detailed Description"
.PP 
Case Constants class\&. 
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure simulation_globals::constants_t::setgravity ()\fC [private]\fP"

.SS "procedure simulation_globals::constants_t::setrho ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "type(vector) simulation_globals::constants_t::gravity\fC [private]\fP"

.PP
Gravitational acceleration vector (default=(0 0 -9\&.81)) (m s-2) 
.SS "real(prec) simulation_globals::constants_t::rho_ref = 1000\&.0\fC [private]\fP"

.PP
Reference density of the medium (default=1000\&.0) (kg m-3) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
