.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_globals.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_globals.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBsimulation_globals::parameters_t\fP"
.br
.ti -1c
.RI "type \fBsimulation_globals::simdefs_t\fP"
.br
.RI "Simulation definitions class\&. "
.ti -1c
.RI "type \fBsimulation_globals::constants_t\fP"
.br
.RI "Case Constants class\&. "
.ti -1c
.RI "type \fBsimulation_globals::filenames_t\fP"
.br
.RI "File names class\&. "
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsimulation_globals\fP"
.br
.RI "Module to hold the simulation global parameter classes and their methods\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsimulation_globals::setparameter\fP (self, parmkey, parmvalue)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::check\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::printsimparameters\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::getintegratorname\fP (name, code)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::setgravity\fP (self, grav)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::setrho\fP (self, read_rho)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::setdp\fP (self, read_dp)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::setdt\fP (self, read_dt)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::setboundingbox\fP (self, point_, coords)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsimulation_globals::printsimdefs\fP (self)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(prec_time), public \fBsimulation_globals::simtime\fP"
.br
.ti -1c
.RI "type(parameters_t), public \fBsimulation_globals::parameters\fP"
.br
.ti -1c
.RI "type(simdefs_t), public \fBsimulation_globals::simdefs\fP"
.br
.ti -1c
.RI "type(constants_t), public \fBsimulation_globals::constants\fP"
.br
.ti -1c
.RI "type(filenames_t), public \fBsimulation_globals::filenames\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
