.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_precision.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/simulation_precision.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsimulation_precision\fP"
.br
.RI "Module to control the precision of the variables trough the project\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBsimulation_precision::sp\fP = kind(1\&._R4P)"
.br
.RI "Simple precision definition switch\&. "
.ti -1c
.RI "integer, parameter \fBsimulation_precision::dp\fP = kind(1\&._R8P)"
.br
.RI "Double precision definition switch\&. "
.ti -1c
.RI "integer, parameter, public \fBsimulation_precision::prec\fP = sp"
.br
.ti -1c
.RI "integer, parameter, public \fBsimulation_precision::prec_time\fP = sp"
.br
.ti -1c
.RI "integer, parameter, public \fBsimulation_precision::prec_wrt\fP = sp"
.br
.ti -1c
.RI "real(prec), parameter, public \fBsimulation_precision::missing_value_default\fP = \-9999\&.0_dp"
.br
.ti -1c
.RI "real(prec), parameter, public \fBsimulation_precision::mv\fP = MISSING_VALUE_DEFAULT"
.br
.ti -1c
.RI "real(prec), parameter, public \fBsimulation_precision::mv_int\fP = int(MISSING_VALUE_DEFAULT)"
.br
.ti -1c
.RI "real(prec), parameter, public \fBsimulation_precision::err_dist\fP = 1E8_dp"
.br
.ti -1c
.RI "integer, parameter, public \fBsimulation_precision::err_ind\fP = \-1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
