.TH "sources" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources \- Module to hold and wrap all the tracer sources respective modules\&. Defines a source class and related methods\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Module to hold and wrap all the tracer sources respective modules\&. Defines a source class and related methods\&. 


.PP
\fBAuthor:\fP
.RS 4
Ricardo Birjukovs Canelas 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
