.TH "source_identity::source_stats" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source_identity::source_stats \- Type - statistical variables of a source object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer \fBparticles_emitted\fP"
.br
.RI "Number of emitted particles by this source\&. "
.ti -1c
.RI "real(prec_wrt) \fBacc_t\fP"
.br
.RI "Accumulated temperature of the tracer (Celcius) "
.ti -1c
.RI "integer \fBns\fP"
.br
.RI "Number of sampling steps\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - statistical variables of a source object\&. 
.SH "Member Data Documentation"
.PP 
.SS "real(prec_wrt) source_identity::source_stats::acc_t\fC [private]\fP"

.PP
Accumulated temperature of the tracer (Celcius) 
.SS "integer source_identity::source_stats::ns\fC [private]\fP"

.PP
Number of sampling steps\&. 
.SS "integer source_identity::source_stats::particles_emitted\fC [private]\fP"

.PP
Number of emitted particles by this source\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
