.TH "source_emitter::emitter_t" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source_emitter::emitter_t
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBinitialize\fP"
.br
.ti -1c
.RI "procedure \fBalloctracers\fP"
.br
.ti -1c
.RI "procedure \fBinitracers\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer \fBemitted\fP"
.br
.ti -1c
.RI "integer \fBemittable\fP"
.br
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure source_emitter::emitter_t::alloctracers ()\fC [private]\fP"

.SS "procedure source_emitter::emitter_t::initialize ()\fC [private]\fP"

.SS "procedure source_emitter::emitter_t::initracers ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "integer source_emitter::emitter_t::emittable\fC [private]\fP"

.SS "integer source_emitter::emitter_t::emitted\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
