.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/source_identity.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/source_identity.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBsource_identity::source_par\fP"
.br
.ti -1c
.RI "type \fBsource_identity::source_state\fP"
.br
.RI "Type - state variables of a source object\&. "
.ti -1c
.RI "type \fBsource_identity::source_stats\fP"
.br
.RI "Type - statistical variables of a source object\&. "
.ti -1c
.RI "type \fBsource_identity::source_stencil\fP"
.br
.RI "Type - holder for the tracer creation stencil of the source\&. "
.ti -1c
.RI "type \fBsource_identity::source_class\fP"
.br
.RI "Type - The source class\&. "
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsource_identity\fP"
.br
.RI "Module that defines a source class and related methods\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsource_identity::allocsources\fP (nsources)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine, public \fBsource_identity::setsourceproperties\fP (srcid_str, ptype, pname)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_identity::initialize\fP (src, id, name, emitting_rate, start, finish, source_geometry, geometry)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_identity::linkproperty\fP (src, ptype, pname)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_identity::printout\fP (src)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(source_class), dimension(:), allocatable, public \fBsource_identity::source\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
