.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/source_emitter.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/source_emitter.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBsource_emitter::emitter_t\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsource_emitter\fP"
.br
.RI "Module that defines an emitter class and related methods\&. This module is responsible for building a potential tracer list based on the availble sources and calling their initializers\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsource_emitter::initracers\fP (self, srcs)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_emitter::alloctracers\fP (self, srcs)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_emitter::initialize\fP (self, srcs)"
.br
.RI "Birjukovs Canelas - MARETEC "
.ti -1c
.RI "subroutine \fBsource_emitter::setotalnp\fP (src)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(emitter_t), public \fBsource_emitter::emitter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
