.TH "source_identity::source_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source_identity::source_class \- Type - The source class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBinitialize\fP"
.br
.ti -1c
.RI "procedure \fBlinkproperty\fP"
.br
.ti -1c
.RI "procedure \fBprintout\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(\fBsource_par\fP) \fBpar\fP"
.br
.RI "To access parameters\&. "
.ti -1c
.RI "type(\fBsource_state\fP) \fBnow\fP"
.br
.RI "To access state variables\&. "
.ti -1c
.RI "type(\fBsource_stencil\fP) \fBstencil\fP"
.br
.RI "To acess stencil variables\&. "
.ti -1c
.RI "type(\fBsource_stats\fP) \fBstats\fP"
.br
.RI "To access statistics\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - The source class\&. 
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure source_identity::source_class::initialize ()\fC [private]\fP"

.SS "procedure source_identity::source_class::linkproperty ()\fC [private]\fP"

.SS "procedure source_identity::source_class::printout ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "type(\fBsource_state\fP) source_identity::source_class::now\fC [private]\fP"

.PP
To access state variables\&. 
.SS "type(\fBsource_par\fP) source_identity::source_class::par\fC [private]\fP"

.PP
To access parameters\&. 
.SS "type(\fBsource_stats\fP) source_identity::source_class::stats\fC [private]\fP"

.PP
To access statistics\&. 
.SS "type(\fBsource_stencil\fP) source_identity::source_class::stencil\fC [private]\fP"

.PP
To acess stencil variables\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
