.TH "tracer_paper::paper_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracer_paper::paper_class \- Type - The plastic material Lagrangian tracer class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtracer_base::tracer_class\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBinitialize\fP => \fBpaper_initialize\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(\fBpaper_par_class\fP) \fBmpar\fP"
.br
.RI "To access material parameters\&. "
.ti -1c
.RI "type(\fBpaper_state_class\fP) \fBmnow\fP"
.br
.RI "To access material state variables\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - The plastic material Lagrangian tracer class\&. 
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure tracer_paper::paper_class::initialize ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "type(\fBpaper_state_class\fP) tracer_paper::paper_class::mnow\fC [private]\fP"

.PP
To access material state variables\&. 
.SS "type(\fBpaper_par_class\fP) tracer_paper::paper_class::mpar\fC [private]\fP"

.PP
To access material parameters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
