.TH "tracer_plastic::plastic_par_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracer_plastic::plastic_par_class
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real(prec) \fBdensity\fP"
.br
.RI "density of the material "
.ti -1c
.RI "real(prec) \fBdegradation_rate\fP"
.br
.RI "degradation rate of the material "
.ti -1c
.RI "logical \fBparticulate\fP"
.br
.RI "flag to indicate if the material is a particle (false) or a collection of particles (true) "
.ti -1c
.RI "real(prec) \fBsize\fP"
.br
.RI "Size (radius) of the particles (equals to the tracer radius if particulate==false) "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "real(prec) tracer_plastic::plastic_par_class::degradation_rate\fC [private]\fP"

.PP
degradation rate of the material 
.SS "real(prec) tracer_plastic::plastic_par_class::density\fC [private]\fP"

.PP
density of the material 
.SS "logical tracer_plastic::plastic_par_class::particulate\fC [private]\fP"

.PP
flag to indicate if the material is a particle (false) or a collection of particles (true) 
.SS "real(prec) tracer_plastic::plastic_par_class::size\fC [private]\fP"

.PP
Size (radius) of the particles (equals to the tracer radius if particulate==false) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
