.TH "tracer_base::tracer_stats_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracer_base::tracer_stats_class \- Type - statistical variables of a pure Lagrangian tracer object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(vector) \fBacc_pos\fP"
.br
.RI "Accumulated position of the tracer (m) "
.ti -1c
.RI "type(vector) \fBacc_vel\fP"
.br
.RI "Accumulated velocity of the tracer (m s-1) "
.ti -1c
.RI "real(prec_wrt) \fBacc_depth\fP"
.br
.RI "Accumulated depth of the tracer (m) "
.ti -1c
.RI "integer \fBns\fP"
.br
.RI "Number of sampling steps\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - statistical variables of a pure Lagrangian tracer object\&. 
.SH "Member Data Documentation"
.PP 
.SS "real(prec_wrt) tracer_base::tracer_stats_class::acc_depth\fC [private]\fP"

.PP
Accumulated depth of the tracer (m) 
.SS "type(vector) tracer_base::tracer_stats_class::acc_pos\fC [private]\fP"

.PP
Accumulated position of the tracer (m) 
.SS "type(vector) tracer_base::tracer_stats_class::acc_vel\fC [private]\fP"

.PP
Accumulated velocity of the tracer (m s-1) 
.SS "integer tracer_base::tracer_stats_class::ns\fC [private]\fP"

.PP
Number of sampling steps\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
