.TH "tracer_paper::paper_state_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracer_paper::paper_state_class \- Type - State variables of a tracer object representing a paper material\&.  

.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "real(prec) \fBradius\fP"
.br
.RI "Tracer radius (m) "
.ti -1c
.RI "real(prec) \fBcondition\fP"
.br
.RI "Material condition (1-0) "
.ti -1c
.RI "real(prec) \fBconcentration\fP"
.br
.RI "Particle concentration\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - State variables of a tracer object representing a paper material\&. 
.SH "Member Data Documentation"
.PP 
.SS "real(prec) tracer_paper::paper_state_class::concentration\fC [private]\fP"

.PP
Particle concentration\&. 
.SS "real(prec) tracer_paper::paper_state_class::condition\fC [private]\fP"

.PP
Material condition (1-0) 
.SS "real(prec) tracer_paper::paper_state_class::radius\fC [private]\fP"

.PP
Tracer radius (m) 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
