.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/tracers.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/tracers.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBtracers\fP"
.br
.RI "Module to hold and wrap all the tracer respective modules\&. Defines a pure Lagrangian tracer block\&. This is intended to serve as the base class for every type of tracer class needed, that should be built as derived of this class, with the necessary modifiers to model the desired behaviour\&. Basic tracer data (parameters, variables) are implemented\&. Tracer methods such as I/O, integration and interpolation routines are implemented\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
