.TH "C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/tracer_plastic.f90" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/administrator/Documents/GitHub/MOHID-Lagrangian/src/lib/tracer_plastic.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBtracer_plastic::plastic_par_class\fP"
.br
.ti -1c
.RI "type \fBtracer_plastic::plastic_state_class\fP"
.br
.RI "Type - State variables of a tracer object representing a plastic material\&. "
.ti -1c
.RI "type \fBtracer_plastic::plastic_class\fP"
.br
.RI "Type - The plastic material Lagrangian tracer class\&. "
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBtracer_plastic\fP"
.br
.RI "Module that defines a Lagrangian tracer class for plastic modelling and related methods\&. The type is defined as a derived type from the pule Lagrangian tracer, and hence inherits all of it's data and methods\&. "
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBtracer_plastic::plastic_initialize\fP (trc, id, id_source, time, pt)"
.br
.RI "Birjukovs Canelas - MARETEC "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
