.TH "tracer_base::tracer_class" 3 "Wed May 2 2018" "Version 0.01" "MOHIDLagrangian" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracer_base::tracer_class \- Type - The pure Lagrangian tracer class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtracer_paper::paper_class\fP, and \fBtracer_plastic::plastic_class\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "procedure \fBinitialize\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "type(\fBtracer_par_class\fP) \fBpar\fP"
.br
.RI "To access parameters\&. "
.ti -1c
.RI "type(\fBtracer_state_class\fP) \fBnow\fP"
.br
.RI "To access state variables\&. "
.ti -1c
.RI "type(\fBtracer_stats_class\fP) \fBstats\fP"
.br
.RI "To access statistics\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type - The pure Lagrangian tracer class\&. 
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "procedure tracer_base::tracer_class::initialize ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "type(\fBtracer_state_class\fP) tracer_base::tracer_class::now\fC [private]\fP"

.PP
To access state variables\&. 
.SS "type(\fBtracer_par_class\fP) tracer_base::tracer_class::par\fC [private]\fP"

.PP
To access parameters\&. 
.SS "type(\fBtracer_stats_class\fP) tracer_base::tracer_class::stats\fC [private]\fP"

.PP
To access statistics\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MOHIDLagrangian from the source code\&.
