name: MOHID-Lagrangian
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=20.3.0
  - blas=1.0
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - cftime=1.2.1
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.0
  - cloudpickle=1.6.0
  - contextvars=2.4
  - cryptography=3.1.1
  - curl=7.67.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - dbus=1.13.18
  - descartes=1.1.0
  - distributed=2.30.0
  - expat=2.2.10
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.3
  - future=0.18.2
  - gdal=2.3.3
  - geopandas=0.6.1
  - geos=3.7.1
  - giflib=5.1.4
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - immutables=0.14
  - intel-openmp=2020.2
  - jinja2=2.11.2
  - jpeg=9b
  - json-c=0.13.1
  - jsoncpp=1.8.4
  - kealib=1.4.7
  - kiwisolver=1.3.0
  - krb5=1.16.4
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libcurl=7.67.0
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=2.3.3
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libllvm10=10.0.1
  - libnetcdf=4.6.1
  - libogg=1.3.2
  - libpng=1.6.37
  - libpq=11.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtheora=1.1.1
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvorbis=1.3.7
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.34.0
  - locket=0.2.0
  - lxml=4.6.1
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msgpack-python=1.0.0
  - munch=2.5.0
  - ncurses=6.2
  - netcdf4=1.4.2
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1h
  - owslib=0.18.0
  - packaging=20.4
  - pandas=1.1.3
  - partd=1.1.0
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.40.0
  - poppler=0.65.0
  - poppler-data=0.4.10
  - proj4=5.2.0
  - psutil=5.7.2
  - pycparser=2.20
  - pyepsg=0.4.0
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyshp=2.1.2
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=7.0
  - requests=2.24.0
  - rtree=0.9.4
  - scipy=1.5.2
  - setuptools=50.3.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.15.0
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - tbb=2020.3
  - tblib=1.7.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - vtk=8.2.0
  - wheel=0.35.1
  - xarray=0.16.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.3.7

