finalize
subroutine finalize::simulation_end
Birjukovs Canelas - MARETEC
Private closing statement routine.
Referenced by finalizemohidlagrangian.
subroutine finalize::deallocate_simulation
Birjukovs Canelas - MARETEC
Private globals deallocation routine.
References source_identity::source, tracer_base::tracer.
Referenced by finalizemohidlagrangian.
subroutine finalize::closelog
Birjukovs Canelas - MARETEC
Private logfile closing routine.
Referenced by finalizemohidlagrangian.
subroutine, public finalize::finalizemohidlagrangian
Birjukovs Canelas - MARETEC
Public finalization routine. Destroys, deallocates and closes the simulation space
References simulation_end, deallocate_simulation, closelog.