simulation_xmlparser
subroutine, public simulation_xmlparser::readxmlatt(xmlnode, tag, att_name, att_value, mandatory)
Birjukovs Canelas - MARETEC
Private attribute xml parser routine. In the format <Tag att_name="att_value" xmlnode tag vec mandatory xmlnode Working xml node tag Tag to search in xml node att_name Atribute name to collect from tag att_value Attribute value mandatory Swich for optional or mandatory tags
Referenced by initialize::init_properties, initialize::init_sources, initialize::init_simdefs, initialize::init_caseconstants.
subroutine, public simulation_xmlparser::readxmlvector(xmlnode, tag, vec, mandatory)
Birjukovs Canelas - MARETEC
Private vector xml parser routine. Vector must be in format <Tag x="vec%x" y="vec%y" z="vec%z"> xmlnode tag vec mandatory xmlnode Working xml node tag Tag to search in xml node vec Vector to fill with read contents mandatory Swich for optional or mandatory tags
Referenced by initialize::read_xml_geometry, initialize::init_simdefs, initialize::init_caseconstants.
subroutine, public simulation_xmlparser::gotochildnode(currentNode, targetNode, targetNodeName, mandatory)
Birjukovs Canelas - MARETEC
Private routine to retrieve a node within a node. Returns a nullifyed pointer if not found, stops if mandatory. currentNode targetNode targetNodeName mandatory mandatory Swich for optional or mandatory tags
Referenced by initialize::init_properties, initialize::init_sources, initialize::init_simdefs, initialize::init_caseconstants, initialize::init_parameters, initialize::initmohidlagrangian.