initialize
subroutine initialize::linkpropertysources(linksNode)
Birjukovs Canelas - MARETEC
Private property xml parser routine. Reads the properties tab from the xml file and links these to the corresponding source parsedxml
References source_identity::setsourceproperties.
Referenced by init_properties.
subroutine initialize::init_properties(case_node)
Birjukovs Canelas - MARETEC
Private property xml parser routine. Reads the properties tab from the xml file and links these to the corresponding source parsedxml
References simulation_xmlparser::gotochildnode, simulation_xmlparser::readxmlatt, simulation_globals::filenames, linkpropertysources.
Referenced by initmohidlagrangian.
subroutine initialize::read_xml_geometry(source, source_detail, geometry)
Birjukovs Canelas - MARETEC
Private geometry xml parser routine. Reads a geometry from the xml depending on the geometry type of the node source geometry source Working xml node source_detail Working xml node details geometry Geometrical object to fill
References simulation_xmlparser::readxmlvector.
Referenced by init_sources.
subroutine initialize::init_sources(case_node)
Birjukovs Canelas - MARETEC
Private source definitions parser routine. Builds the tracer sources from the input xml case file. parsedxml
References simulation_xmlparser::gotochildnode, source_identity::allocsources, simulation_xmlparser::readxmlatt, simulation_globals::parameters, read_xml_geometry, source_identity::source.
Referenced by initmohidlagrangian.
subroutine initialize::init_simdefs(case_node)
Birjukovs Canelas - MARETEC
Private simulation definitions parser routine. Builds the simulation geometric space from the input xml case file. parsedxml
References simulation_xmlparser::gotochildnode, simulation_xmlparser::readxmlatt, simulation_globals::simdefs, simulation_xmlparser::readxmlvector.
Referenced by initmohidlagrangian.
subroutine initialize::init_caseconstants(case_node)
Birjukovs Canelas - MARETEC
Private case constant parser routine. Builds the simulation parametric space from the input xml case file. parsedxml
References simulation_xmlparser::gotochildnode, simulation_xmlparser::readxmlvector, simulation_globals::constants, simulation_xmlparser::readxmlatt.
Referenced by initmohidlagrangian.
subroutine initialize::init_parameters(execution_node)
Birjukovs Canelas - MARETEC
Private parameter parser routine. Builds the simulation parametric space from the input xml case file. parsedxml
References simulation_xmlparser::gotochildnode, simulation_globals::parameters.
Referenced by initmohidlagrangian.
subroutine, public initialize::initmohidlagrangian(xmlfilename)
Birjukovs Canelas - MARETEC
Public xml parser routine. Builds the simulation space from the input xml case file. xmlfilename xmlfilename .xml file name
References about::printlicpreamble, simulation_globals::simtime, simulation_globals::filenames, simulation_xmlparser::gotochildnode, init_parameters, init_caseconstants, init_simdefs, init_sources, init_properties, source_emitter::emitter, source_identity::source.