geometry
type(string), dimension(:), allocatable, public geometry::geomlist
String list (array) with the name of possible geometry types.
Referenced by allocategeomlist, isvalidgeom.
subroutine, public geometry::allocategeomlist
Birjukovs Canelas - MARETEC
Public routine to allocate the possible geometry name list
References geomlist.
logical function, public geometry::isvalidgeom(geomname)
Birjukovs Canelas - MARETEC
Public function that returns a logical if the input geometry name is valid geomname
References geomlist.
subroutine geometry::getnp(self, np, dp)
Birjukovs Canelas - MARETEC
method to get the number of points that fill a given geometry self np
References sphere_np_count, simulation_logger::tolog.
subroutine geometry::getpointdistribution(self, np, dp, ptlist)
Birjukovs Canelas - MARETEC
method to get the number of points that fill a given geometry self np
References box_grid, line_grid, sphere_grid, simulation_logger::tolog.
subroutine geometry::sphere_np_count(dp, r, np)
Birjukovs Canelas - MARETEC
private routine that returns the number of points distributed on a grid with spacing dp inside a sphere dp r np
Referenced by getnp.
subroutine geometry::sphere_grid(dp, r, np, ptlist)
Birjukovs Canelas - MARETEC
private routine that returns the points distributed on a grid with spacing dp inside a sphere dp r np ptlist
Referenced by getpointdistribution.
subroutine geometry::box_grid(dp, size, np, ptlist)
Birjukovs Canelas - MARETEC
private routine that returns the points distributed on a grid with spacing dp inside a box dp size np ptlist
Referenced by getpointdistribution.
subroutine geometry::line_grid(dp, dist, np, ptlist)
Birjukovs Canelas - MARETEC
private routine that returns the points distributed on a grid with spacing dp along a line dp size np ptlist
Referenced by getpointdistribution.