simulation_logger
integer, public simulation_logger::log_unit
'Number' of log file
Referenced by tolog, initmohidlagrangianlog.
subroutine, public simulation_logger::gettimestamp(timestamp)
Birjukovs Canelas - MARETEC
Public timestamp builder timestamp
Referenced by tolog.
subroutine, public simulation_logger::tolog(tologstr, timeoption)
Birjukovs Canelas - MARETEC
Public log serialization routine outpath
References gettimestamp, log_unit.
Referenced by geometry::getnp, geometry::getpointdistribution, simulation_globals::check, simulation_globals::printsimparameters, simulation_globals::setrho, simulation_globals::setdp, simulation_globals::setdt, simulation_globals::printsimdefs, simulation_memory::printmemory, simulation_memory::printmemorydetailed.
subroutine, public simulation_logger::initmohidlagrangianlog(outpath)
Birjukovs Canelas - MARETEC
Public log file initizalization routine. outpath
References log_unit.